%%% bin satellite Chla daily data into time-series dataset (supplement missing days with NA matrix)

close all
clear all

%% pick out the missing days in time series dataset
% list out the files in the folder 
folder='...' % open folder where coverted .mat files are (generated by runhdf_chla.m) 
cd(folder)
list2=dir('*.mat');
timespan = datetime(1996,11,1):datetime(2020,5,12) %create normal timespan. Change the end date if you use up-to-date data
%verify the existence of data
bug = zeros(length(timespan),1); %list of which day is missing
for i = 1:length(timespan)
    yr = year(timespan(i));
    doy = day(timespan(i),'dayofyear'); 
    bug(i)=exist(['chla_',num2str(yr),'_',num2str(doy),'.mat']);  
end
%put missing data into list (year-day)
daymiss = find(bug==0)+datenum(1996,11,1)-1
datemiss = table();
for i=1:length(daymiss)
    datemiss.date(i,1) = datetime(daymiss(i),'ConvertFrom','datenum');
    datemiss.dayofyear(i,1) = day(datemiss.date(i,1),'dayofyear');
end
addpath folder

order= datemiss.date; %the missing days in npp dataset
chla_full=[];
%integrate Chla datasets
cd('...'); %% same folder where coverted .mat files are (generated by runhdf_chla.m) 
for i = 1:length(timespan)
    d=datetime(i+datenum(1996,11,1)-1,'ConvertFrom','datenum');%consider the duplicated issue at the start and the end of each year
    tf = ismember(d, order) %date that doesn't exist in both st_sate & ed_date
    yr = year(timespan(i));
    doy = day(timespan(i),'dayofyear');
    if tf
        chla_full(:,:,i)=NaN(417,540);% create NA matrices for missing days
    else
        yr = year(timespan(i));
        doy = day(timespan(i),'dayofyear'); 
        load(['chla_',num2str(yr),'_',num2str(doy),'.mat']);  
        chla_full(:,:,i)=chla_final;
    end
end

%save the output
cd ('...')
save("chla_full_mid.mat",'chla_full',"-v7.3")


